version: "3.8"
services:
  app:
    build: ./backend
    ports: 
      - 3000:3000
    environment:
      DB_URL: mongodb://db/sg
      depends_on:
        - db
  db:
    image: mongo:4.0-xenial
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - sg:/data/db
  volumes:
    sg: 


