name: Flask App CI

on:
  push:
    branches:
      - main  # or your default branch name
  pull_request:
    branches:
      - main  # or your default branch name

jobs:
  test:
    runs-on: ubuntu-latest  # Running the tests on the latest Ubuntu image

    services:
      mongo:
        image: mongo:latest  # Use the official MongoDB Docker image
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.adminCommand('ping')'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v3  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Choose your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "MONGO_URI=mongodb://localhost:27017/test_db" >> $GITHUB_ENV
          echo "MONGO_DBNAME=test_db" >> $GITHUB_ENV  # Set Mongo URI and database for testing
          echo "FLASK_APP=app.py" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Run your tests using pytest