name: Web App CI/CD

on: [pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --health-cmd="curl --silent --fail localhost:27017 || exit 1" --health-interval=30s --health-timeout=30s --health-retries=3
        
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python, pipenv and Pipfile packages
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        run: |
          pytest -v tests/